language: csharp
dotnet: 2.2.301

sudo: false  # use the new container-based Travis infrastructure 

before_install:
  - chmod +x build.sh
 
script: 
  - ./build.sh -t GenerateDocs # this will run 'RunTests' as well
env:
  FSHARP_FORMATTING_LOG=NONE
  