language: csharp
dotnet: 6.0.201 

sudo: false  # use the new container-based Travis infrastructure 

script: 
  - dotnet restore ./FSharpPlus.sln
  - dotnet build -c Release ./FSharpPlus.sln
  - dotnet test -c Release tests/FSharpPlus.Tests
  - ./docsrc/tools/download_nugets.sh
  - sudo apt-get install -y dotnet-sdk-3.1 # F# Formatting
  - dotnet run -c Release --project ./docsrc/tools

env:
  FSHARP_FORMATTING_LOG=NONE