language: csharp
dotnet: 3.0.101

sudo: false  # use the new container-based Travis infrastructure 

script: 
  - dotnet restore ./FSharpPlus.sln
  - dotnet build -c Release ./FSharpPlus.sln
  - dotnet test -c Release tests/FSharpPlus.Tests
env:
  FSHARP_FORMATTING_LOG=NONE
branches:
  only: 
    - master